apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nostro
  template:
    metadata:
      labels:
        app: nostro
    spec:
      containers:
      - name: nostro
        image: your/nostro-image:version
        env:
        - name: ORACLE_SID
          value: YOUR_ORACLE_SID
        - name: ORACLE_PDB
          value: YOUR_ORACLE_PDB
        - name: ORACLE_PWD
          valueFrom:
            secretKeyRef:
              name: oracle-secret
              key: oracle-password
        - name: ORACLE_LISTENER_PORT
          value: "1521"
        - name: ORACLE_CHARACTERSET
          value: "AL32UTF8"
        - name: ORACLE_TOTAL_MEMORY
          value: "2G"
        ports:
        - containerPort: 1521
