kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: nginx-scc
priority: 10
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
readOnlyRootFilesystem: false
users:
- system:serviceaccount:sftp:default
